### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Corey935xx** [AlexModGuy/AlexsCaves#1097]
so i use multi mc launcher and this exit code keeps popping up even though its 1.20.1 and im using 1.20.1 

MultiMC version: 0.7.0-3863

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.253.64]

textures.minecraft.net resolves to:
    [13.107.253.64]

api.mojang.com resolves to:
    [13.107.253.64]

Minecraft folder is:
D:/MultiMC/mmc-develop-win32 (1)/MultiMC/instances/Minecraft create w jacobi survival/.minecraft

Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe

Checking Java version...
Java is version 17.0.10, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/instances/Minecraft create w jacobi survival/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc5/ForgeWrapper-mmc5.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/eventbus/6.0.5/eventbus-6.0.5.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/forgespi/7.0.1/forgespi-7.0.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/cpw/mods/modlauncher/10.0.9/modlauncher-10.0.9.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/mergetool/1.1.5/mergetool-1.1.5-api.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/fmlloader/1.20.1-47.2.0/fmlloader-1.20.1-47.2.0.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/fmlearlydisplay/1.20.1-47.2.0/fmlearlydisplay-1.20.1-47.2.0.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  D:/MultiMC/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [✔️] [1.20.1] SecurityCraft v1.9.9.jar
  [✔️] alexscaves-1.1.4.jar
  [✔️] All the Create Addons-1.0.0.zip
  [✔️] badpackets-forge-0.4.3.jar
  [✔️] create-1.20.1-0.5.1.f.jar
  [✔️] create-confectionery1.20.1_v1.1.0.jar
  [✔️] createsifter-1.20.1-1.8.1.e-22.jar
  [✔️] create-structures-0.1.1-1.20.1-FORGE.jar
  [✔️] essential_1-3-2-5_forge_1-20-1.jar
  [✔️] jei-1.20.1-forge-15.3.0.4.jar
  [✔️] journeymap-1.20.1-5.9.22-forge.jar
  [✔️] Steam_Rails-1.6.4+forge-mc1.20.1.jar
  [✔️] storagedrawers-1.20.1-12.0.2.jar
  [✔️] wthit-forge-8.11.0.jar

Params:
  --username corey935 --version 1.20.1 --gameDir D:/MultiMC/mmc-develop-win32 (1)/MultiMC/instances/Minecraft create w jacobi survival/.minecraft --assetsDir D:/MultiMC/mmc-develop-win32 (1)/MultiMC/assets --assetIndex 5 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release --launchTarget forgeclient --fml.forgeVersion 47.2.0 --fml.mcVersion 1.20.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230612.114412

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 17252

Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2024-06-07 18:57:29,918 main WARN Advanced terminal features are not available in this environment
[18:57:30] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, corey935, --version, 1.20.1, --gameDir, D:/MultiMC/mmc-develop-win32 (1)/MultiMC/instances/Minecraft create w jacobi survival/.minecraft, --assetsDir, D:/MultiMC/mmc-develop-win32 (1)/MultiMC/assets, --assetIndex, 5, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[18:57:30] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.10 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[18:57:31] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[18:57:31] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[18:57:32] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[18:57:32] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: AMD Radeon(TM) Graphics GL version 4.6.0 Core Profile Context 22.20.14.220712, ATI Technologies Inc.
[18:57:34] [main/INFO] [gg.es.lo.st.EssentialLoaderBase/]: Starting Essential Loader (stage2) version 1.6.2 (285f951adc7537f49ae3ef9fc0d2fd3e) [stable]
[18:57:34] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/MultiMC/mmc-develop-win32%20(1)/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23122!/ Service=ModLauncher Env=CLIENT
[18:57:36] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file D:\MultiMC\mmc-develop-win32 (1)\MultiMC\libraries\net\minecraftforge\fmlcore\1.20.1-47.2.0\fmlcore-1.20.1-47.2.0.jar is missing mods.toml file
[18:57:36] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file D:\MultiMC\mmc-develop-win32 (1)\MultiMC\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.0\javafmllanguage-1.20.1-47.2.0.jar is missing mods.toml file
[18:57:36] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file D:\MultiMC\mmc-develop-win32 (1)\MultiMC\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.0\lowcodelanguage-1.20.1-47.2.0.jar is missing mods.toml file
[18:57:36] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file D:\MultiMC\mmc-develop-win32 (1)\MultiMC\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.0\mclanguage-1.20.1-47.2.0.jar is missing mods.toml file
[18:57:36] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 4 dependencies adding them to mods collection
[18:57:36] [main/INFO] [gg.es.lo.st.ut.KFFMerger/]: Found Kotlin-containing mod Jar[union:/D:/MultiMC/mmc-develop-win32%20(1)/MultiMC/instances/Minecraft%20create%20w%20jacobi%20survival/.minecraft/essential/libraries/forge_1.20.1/kotlin-for-forge-4.3.0-slim.jar%23151!/], checking whether we need to upgrade it..
[18:57:36] [main/INFO] [gg.es.lo.st.ut.KFFMerger/]: Found outdated Kotlin core libs 0.0.0 (we ship 1.9.23)
[18:57:36] [main/INFO] [gg.es.lo.st.ut.KFFMerger/]: Found outdated Kotlin Coroutines libs 0.0.0 (we ship 1.8.0)
[18:57:36] [main/INFO] [gg.es.lo.st.ut.KFFMerger/]: Found outdated Kotlin Serialization libs 0.0.0 (we ship 1.6.3)
[18:57:36] [main/INFO] [gg.es.lo.st.ut.KFFMerger/]: Generating jar with updated Kotlin at C:\Users\webst\AppData\Local\Temp\kff-updated-kotlin-14934560880878056762-4.3.0-slim.jar
[18:57:38] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'citadel', Requested by: 'alexscaves', Expected range: '[2.5.3,)', Actual version: '[MISSING]'
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config citadel.mixins.json
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:262)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:46)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:122)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:144)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:134)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.addNestedContainers(MixinPlatformManager.java:152)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.scanForContainers(MixinPlatformManager.java:213)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:186)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:34)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$11(LaunchPluginHandler.java:100)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:100)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:51)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 13 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'citadel.mixins.json' was invalid or could not be read
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1282)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 36 more
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 07 Jun 2024 18:57:47 +0100

**Comment by Lucky-56** [comment]
you're missing citadel:
`[18:57:38] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
Mod ID: 'citadel', Requested by: 'alexscaves', Expected range: '[2.5.3,)', Actual version: '[MISSING]'`

please close, as this is not an issue with the mod itself
