### ISSUE TITLE
crash report: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.EntityDimensions net.minecraftforge.event.entity.EntityEvent$Size.getOldSize()'

### ISSUE THREAD

**Issue by ElRuso0** [AlexModGuy/AlexsCaves#118]
First time en github, idk how to let you know about issues but here's my try.

Error Code: -1

---- Minecraft Crash Report ----
// You're mean.

Time: 2023-10-19 22:18:44
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.world.entity.EntityDimensions net.minecraftforge.event.entity.EntityEvent$Size.getOldSize()'
	at com.github.alexmodguy.alexscaves.server.event.CommonEvents.resizeEntity(CommonEvents.java:59) ~[alexscaves-1.0.2.jar%23165!/:1.0.2] {re:classloading}
	at com.github.alexmodguy.alexscaves.server.event.__CommonEvents_resizeEntity_Size.invoke(.dynamic) ~[alexscaves-1.0.2.jar%23165!/:1.0.2] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:EntityMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_6210_(Entity.java:2728) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:EntityMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:A}
	at com.github.alexthe666.alexsmobs.entity.EntityCatfish.m_7350_(EntityCatfish.java:227) ~[alexsmobs-1.22.6.jar%23166!/:1.22.6] {re:classloading}
	at net.minecraft.network.syncher.SynchedEntityData.m_135356_(SynchedEntityData.java:193) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_6455_(ClientPacketListener.java:502) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.m_5797_(ClientboundSetEntityDataPacket.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.m_5797_(ClientboundSetEntityDataPacket.java:10) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_264308_(ClientPacketListener.java:2305) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:13) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:6) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.28.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.28.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.28.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.28.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.alexmodguy.alexscaves.server.event.CommonEvents.resizeEntity(CommonEvents.java:59) ~[alexscaves-1.0.2.jar%23165!/:1.0.2] {re:classloading}
	at com.github.alexmodguy.alexscaves.server.event.__CommonEvents_resizeEntity_Size.invoke(.dynamic) ~[alexscaves-1.0.2.jar%23165!/:1.0.2] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:EntityMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_6210_(Entity.java:2728) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:EntityMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:A}
	at com.github.alexthe666.alexsmobs.entity.EntityCatfish.m_7350_(EntityCatfish.java:227) ~[alexsmobs-1.22.6.jar%23166!/:1.22.6] {re:classloading}
	at net.minecraft.network.syncher.SynchedEntityData.m_135356_(SynchedEntityData.java:193) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_6455_(ClientPacketListener.java:502) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.m_5797_(ClientboundSetEntityDataPacket.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.m_5797_(ClientboundSetEntityDataPacket.java:10) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_264308_(ClientPacketListener.java:2305) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:13) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:6) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['ElRuso0'/168, l='ClientLevel', x=4.50, y=63.00, z=37.50]]
	Chunk stats: 289, 19
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,72,32), Section: (at 0,8,0 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 10594 game time, 10594 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:alexscaves.mixins.json:client.ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.28.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.28.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.28.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.28.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 448307368 bytes (427 MiB) / 1073741824 bytes (1024 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
	Identifier: Intel64 Family 6 Model 78 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 1.99
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Parsec Virtual Display Adapter
	Graphics card #0 vendor: Parsec Cloud, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=0.41.0.0
	Graphics card #1 name: Intel(R) HD Graphics 520
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x1916
	Graphics card #1 versionInfo: DriverVersion=31.0.101.2111
	Graphics card #2 name: AMD Radeon (TM) R5 M330
	Graphics card #2 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #2 VRAM (MB): 2048.00
	Graphics card #2 deviceId: 0x6660
	Graphics card #2 versionInfo: DriverVersion=27.20.20912.1002
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 12076.90
	Virtual memory used (MB): 10380.18
	Swap memory total (MB): 3968.00
	Swap memory used (MB): 781.61
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.20.1-forge-47.1.28
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Intel(R) HD Graphics 520 GL version 4.6.0 - Build 31.0.101.2111, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: en_us
	CPU: 4x Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.28.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.28.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.28.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.28.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.28.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.1.28-universal.jar                |Forge                         |forge                         |47.1.28             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		sophisticatedcore-1.20.1-0.5.89.425.jar           |Sophisticated Core            |sophisticatedcore             |0.5.89.425          |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.20.1-3.18.59.909.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |3.18.59.909         |DONE      |Manifest: NOSIGNATURE
		essentials-1.20.1-2.16.0.jar                      |Essentials                    |essentials                    |1.20.1-2.16.0       |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.0.2.jar                   |Waystones                     |waystones                     |14.0.2              |DONE      |Manifest: NOSIGNATURE
		citadel-2.4.5-1.20.1.jar                          |Citadel                       |citadel                       |2.4.5               |DONE      |Manifest: NOSIGNATURE
		alexscaves-1.0.2.jar                              |Alex's Caves                  |alexscaves                    |1.0.2               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.6              |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.1.4.jar                       |Balm                          |balm                          |7.1.4               |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.22.jar                    |Just Enough Items             |jei                           |15.2.0.22           |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 762e94a3-cc83-4c53-9fbb-9ca7cf7350d5
	FML: 47.1
	Forge: net.minecraftforge:47.1.28

**Comment by AlexModGuy** [comment]
update forge
