### ISSUE TITLE
Alex's Caves v2.0.2 crash

### ISSUE THREAD

**Issue by A2Ziee** [AlexModGuy/AlexsCaves#1460]
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.player.LocalPlayer.m_21023_(net.minecraft.world.effect.MobEffect)" because "net.minecraft.client.Minecraft.m_91087_().f_91074_" is null
	at net.minecraft.client.renderer.LightTexture.handler$jic000$ac_getBrightness(LightTexture.java:585) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.LightTextureMixin,pl:mixin:APP:majruszsdifficulty-common.mixins.json:MixinLightTexture,pl:mixin:APP:mixins.oculus.json:LightTextureAccessor,pl:mixin:APP:mixins.oculus.json:MixinLightTexture,pl:mixin:APP:freecam.mixins.json:LightTextureMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinLightMapTexture,pl:mixin:APP:blue_skies.mixins.json:LightTextureMixin,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinLightmapManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LightTexture.m_234316_(LightTexture.java:189) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.LightTextureMixin,pl:mixin:APP:majruszsdifficulty-common.mixins.json:MixinLightTexture,pl:mixin:APP:mixins.oculus.json:LightTextureAccessor,pl:mixin:APP:mixins.oculus.json:MixinLightTexture,pl:mixin:APP:freecam.mixins.json:LightTextureMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinLightMapTexture,pl:mixin:APP:blue_skies.mixins.json:LightTextureMixin,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinLightmapManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.Gui.m_93020_(Gui.java:950) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveui-common.mixins.json:InGameHudMixin,pl:mixin:APP:apotheosis.mixins.json:client.GuiMixin,pl:mixin:APP:immersiveui-common.mixins.json:GooeyMixin,pl:mixin:APP:highlighter.mixins.json:GuiMixin,pl:mixin:APP:mixins.oculus.json:gui.MixinGui,pl:mixin:APP:dynamic_fps.mixins.json:GuiMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GuiMixin,pl:mixin:APP:shouldersurfing.common.mixins.json:MixinGui,pl:mixin:APP:bridgingmod.mixins.json:CrosshairRenderingMixin,pl:mixin:APP:obscure_api.mixins.json:client.GuiMixin,pl:mixin:APP:freecam.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:APP:betterf3.mixins.json:scoreboard.ScoreboardMixin,pl:mixin:APP:overflowingbars.common.mixins.json:client.GuiMixin,pl:mixin:APP:mixins.irons_spellbooks.json:GuiMixin,pl:mixin:APP:pehkui.mixins.json:client.compat120plus.InGameHudMixin,pl:mixin:APP:bettercombat.mixins.json:client.InGameHudInject,pl:mixin:APP:aether.mixins.json:client.accessor.GuiAccessor,pl:mixin:APP:immersive_aircraft.mixins.json:client.GuiMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGui,pl:mixin:APP:itemborders.mixins.json:GuiMixin,pl:mixin:APP:oreganized.mixins.json:client.GuiMixin,pl:mixin:APP:quark.mixins.json:client.GuiMixin,pl:mixin:APP:embeddium.mixins.json:features.options.overlays.InGameHudMixin,pl:mixin:APP:structure_gel.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:debugcrosshair.DebugCrosshairMixin,pl:mixin:APP:immediatelyfast-common.mixins.json:hud_batching.MixinInGameHud,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.Gui.m_93066_(Gui.java:1047) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveui-common.mixins.json:InGameHudMixin,pl:mixin:APP:apotheosis.mixins.json:client.GuiMixin,pl:mixin:APP:immersiveui-common.mixins.json:GooeyMixin,pl:mixin:APP:highlighter.mixins.json:GuiMixin,pl:mixin:APP:mixins.oculus.json:gui.MixinGui,pl:mixin:APP:dynamic_fps.mixins.json:GuiMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GuiMixin,pl:mixin:APP:shouldersurfing.common.mixins.json:MixinGui,pl:mixin:APP:bridgingmod.mixins.json:CrosshairRenderingMixin,pl:mixin:APP:obscure_api.mixins.json:client.GuiMixin,pl:mixin:APP:freecam.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:APP:betterf3.mixins.json:scoreboard.ScoreboardMixin,pl:mixin:APP:overflowingbars.common.mixins.json:client.GuiMixin,pl:mixin:APP:mixins.irons_spellbooks.json:GuiMixin,pl:mixin:APP:pehkui.mixins.json:client.compat120plus.InGameHudMixin,pl:mixin:APP:bettercombat.mixins.json:client.InGameHudInject,pl:mixin:APP:aether.mixins.json:client.accessor.GuiAccessor,pl:mixin:APP:immersive_aircraft.mixins.json:client.GuiMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGui,pl:mixin:APP:itemborders.mixins.json:GuiMixin,pl:mixin:APP:oreganized.mixins.json:client.GuiMixin,pl:mixin:APP:quark.mixins.json:client.GuiMixin,pl:mixin:APP:embeddium.mixins.json:features.options.overlays.InGameHudMixin,pl:mixin:APP:structure_gel.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:debugcrosshair.DebugCrosshairMixin,pl:mixin:APP:immediatelyfast-common.mixins.json:hud_batching.MixinInGameHud,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.Gui.m_193832_(Gui.java:1026) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveui-common.mixins.json:InGameHudMixin,pl:mixin:APP:apotheosis.mixins.json:client.GuiMixin,pl:mixin:APP:immersiveui-common.mixins.json:GooeyMixin,pl:mixin:APP:highlighter.mixins.json:GuiMixin,pl:mixin:APP:mixins.oculus.json:gui.MixinGui,pl:mixin:APP:dynamic_fps.mixins.json:GuiMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GuiMixin,pl:mixin:APP:shouldersurfing.common.mixins.json:MixinGui,pl:mixin:APP:bridgingmod.mixins.json:CrosshairRenderingMixin,pl:mixin:APP:obscure_api.mixins.json:client.GuiMixin,pl:mixin:APP:freecam.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:APP:betterf3.mixins.json:scoreboard.ScoreboardMixin,pl:mixin:APP:overflowingbars.common.mixins.json:client.GuiMixin,pl:mixin:APP:mixins.irons_spellbooks.json:GuiMixin,pl:mixin:APP:pehkui.mixins.json:client.compat120plus.InGameHudMixin,pl:mixin:APP:bettercombat.mixins.json:client.InGameHudInject,pl:mixin:APP:aether.mixins.json:client.accessor.GuiAccessor,pl:mixin:APP:immersive_aircraft.mixins.json:client.GuiMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGui,pl:mixin:APP:itemborders.mixins.json:GuiMixin,pl:mixin:APP:oreganized.mixins.json:client.GuiMixin,pl:mixin:APP:quark.mixins.json:client.GuiMixin,pl:mixin:APP:embeddium.mixins.json:features.options.overlays.InGameHudMixin,pl:mixin:APP:structure_gel.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:debugcrosshair.DebugCrosshairMixin,pl:mixin:APP:immediatelyfast-common.mixins.json:hud_batching.MixinInGameHud,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1749) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.3.11.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Alex's Caves (alexscaves), Version: 2.0.2
		Issue tracker URL: https://github.com/AlexModGuy/AlexsCaves/issues
		Mixin class: com.github.alexmodguy.alexscaves.mixin.client.LightTextureMixin
		Target: net.minecraft.client.renderer.LightTexture
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LightTexture.handler$jic000$ac_getBrightness(LightTexture.java:585)
Stacktrace:
	at net.minecraft.client.renderer.LightTexture.handler$jic000$ac_getBrightness(LightTexture.java:585) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.LightTextureMixin,pl:mixin:APP:majruszsdifficulty-common.mixins.json:MixinLightTexture,pl:mixin:APP:mixins.oculus.json:LightTextureAccessor,pl:mixin:APP:mixins.oculus.json:MixinLightTexture,pl:mixin:APP:freecam.mixins.json:LightTextureMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinLightMapTexture,pl:mixin:APP:blue_skies.mixins.json:LightTextureMixin,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinLightmapManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LightTexture.m_234316_(LightTexture.java:189) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.LightTextureMixin,pl:mixin:APP:majruszsdifficulty-common.mixins.json:MixinLightTexture,pl:mixin:APP:mixins.oculus.json:LightTextureAccessor,pl:mixin:APP:mixins.oculus.json:MixinLightTexture,pl:mixin:APP:freecam.mixins.json:LightTextureMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinLightMapTexture,pl:mixin:APP:blue_skies.mixins.json:LightTextureMixin,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinLightmapManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.Gui.m_93020_(Gui.java:950) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveui-common.mixins.json:InGameHudMixin,pl:mixin:APP:apotheosis.mixins.json:client.GuiMixin,pl:mixin:APP:immersiveui-common.mixins.json:GooeyMixin,pl:mixin:APP:highlighter.mixins.json:GuiMixin,pl:mixin:APP:mixins.oculus.json:gui.MixinGui,pl:mixin:APP:dynamic_fps.mixins.json:GuiMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GuiMixin,pl:mixin:APP:shouldersurfing.common.mixins.json:MixinGui,pl:mixin:APP:bridgingmod.mixins.json:CrosshairRenderingMixin,pl:mixin:APP:obscure_api.mixins.json:client.GuiMixin,pl:mixin:APP:freecam.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:APP:betterf3.mixins.json:scoreboard.ScoreboardMixin,pl:mixin:APP:overflowingbars.common.mixins.json:client.GuiMixin,pl:mixin:APP:mixins.irons_spellbooks.json:GuiMixin,pl:mixin:APP:pehkui.mixins.json:client.compat120plus.InGameHudMixin,pl:mixin:APP:bettercombat.mixins.json:client.InGameHudInject,pl:mixin:APP:aether.mixins.json:client.accessor.GuiAccessor,pl:mixin:APP:immersive_aircraft.mixins.json:client.GuiMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGui,pl:mixin:APP:itemborders.mixins.json:GuiMixin,pl:mixin:APP:oreganized.mixins.json:client.GuiMixin,pl:mixin:APP:quark.mixins.json:client.GuiMixin,pl:mixin:APP:embeddium.mixins.json:features.options.overlays.InGameHudMixin,pl:mixin:APP:structure_gel.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:debugcrosshair.DebugCrosshairMixin,pl:mixin:APP:immediatelyfast-common.mixins.json:hud_batching.MixinInGameHud,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.Gui.m_93066_(Gui.java:1047) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveui-common.mixins.json:InGameHudMixin,pl:mixin:APP:apotheosis.mixins.json:client.GuiMixin,pl:mixin:APP:immersiveui-common.mixins.json:GooeyMixin,pl:mixin:APP:highlighter.mixins.json:GuiMixin,pl:mixin:APP:mixins.oculus.json:gui.MixinGui,pl:mixin:APP:dynamic_fps.mixins.json:GuiMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GuiMixin,pl:mixin:APP:shouldersurfing.common.mixins.json:MixinGui,pl:mixin:APP:bridgingmod.mixins.json:CrosshairRenderingMixin,pl:mixin:APP:obscure_api.mixins.json:client.GuiMixin,pl:mixin:APP:freecam.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:APP:betterf3.mixins.json:scoreboard.ScoreboardMixin,pl:mixin:APP:overflowingbars.common.mixins.json:client.GuiMixin,pl:mixin:APP:mixins.irons_spellbooks.json:GuiMixin,pl:mixin:APP:pehkui.mixins.json:client.compat120plus.InGameHudMixin,pl:mixin:APP:bettercombat.mixins.json:client.InGameHudInject,pl:mixin:APP:aether.mixins.json:client.accessor.GuiAccessor,pl:mixin:APP:immersive_aircraft.mixins.json:client.GuiMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGui,pl:mixin:APP:itemborders.mixins.json:GuiMixin,pl:mixin:APP:oreganized.mixins.json:client.GuiMixin,pl:mixin:APP:quark.mixins.json:client.GuiMixin,pl:mixin:APP:embeddium.mixins.json:features.options.overlays.InGameHudMixin,pl:mixin:APP:structure_gel.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:debugcrosshair.DebugCrosshairMixin,pl:mixin:APP:immediatelyfast-common.mixins.json:hud_batching.MixinInGameHud,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.Gui.m_193832_(Gui.java:1026) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveui-common.mixins.json:InGameHudMixin,pl:mixin:APP:apotheosis.mixins.json:client.GuiMixin,pl:mixin:APP:immersiveui-common.mixins.json:GooeyMixin,pl:mixin:APP:highlighter.mixins.json:GuiMixin,pl:mixin:APP:mixins.oculus.json:gui.MixinGui,pl:mixin:APP:dynamic_fps.mixins.json:GuiMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GuiMixin,pl:mixin:APP:shouldersurfing.common.mixins.json:MixinGui,pl:mixin:APP:bridgingmod.mixins.json:CrosshairRenderingMixin,pl:mixin:APP:obscure_api.mixins.json:client.GuiMixin,pl:mixin:APP:freecam.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:APP:betterf3.mixins.json:scoreboard.ScoreboardMixin,pl:mixin:APP:overflowingbars.common.mixins.json:client.GuiMixin,pl:mixin:APP:mixins.irons_spellbooks.json:GuiMixin,pl:mixin:APP:pehkui.mixins.json:client.compat120plus.InGameHudMixin,pl:mixin:APP:bettercombat.mixins.json:client.InGameHudInject,pl:mixin:APP:aether.mixins.json:client.accessor.GuiAccessor,pl:mixin:APP:immersive_aircraft.mixins.json:client.GuiMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGui,pl:mixin:APP:itemborders.mixins.json:GuiMixin,pl:mixin:APP:oreganized.mixins.json:client.GuiMixin,pl:mixin:APP:quark.mixins.json:client.GuiMixin,pl:mixin:APP:embeddium.mixins.json:features.options.overlays.InGameHudMixin,pl:mixin:APP:structure_gel.mixins.json:GuiMixin,pl:mixin:APP:betterf3.mixins.json:debugcrosshair.DebugCrosshairMixin,pl:mixin:APP:immediatelyfast-common.mixins.json:hud_batching.MixinInGameHud,pl:mixin:A,pl:runtimedistcleaner:A}
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources, Moonlight Mods Dynamic Assets, file/Stay_True_1.20.zip, file/Icon Xaero's 1.2 HF.zip, file/xali's Potions v1.0.zip, file/enchant icons 1.20 v1.3.zip, file/Better-Leaves-8.1-1.20+.zip, cullleaves:smartleaves, bushy_leaves, eatinganimations_compat, file/FreshAnimations_v1.9.2.zip, file/FA+Slamacow-v1.1.zip, file/FA+Quivers-v1.1.zip, file/FA+Objects-v1.1.zip, file/FA+Emissive-v1.2.zip, file/FA+Details-v1.1.zip, file/FA+Classic_Horses-v1.2.zip, file/SmoothFont_1.20.zip, file/Icon - Xaero X FA - v2.4 (1.20.x).zip, file/DSWG Realistic Explosion (Frag) 1.20.zip, file/waystones_1.20.zip, file/Lopy-Create-Sophisticated-Backpacks.zip, file/SkinReplacer, twilightdelight:shader_compatible_fiery, supplementaries:darker_ropes, spelunkery:better_vanilla_gems, Steam 'n' Rails Legacy Semaphores, Steam 'n' Rails Legacy Palettes Textures, Steam 'n' Rails Green Signals, file/SE Vanilla Consistency 1.20.1.zip, create_central_kitchen:create_styled, create:legacy_copper, file/Create Immersive Aircrafts Resource Pack 1.20.1 - 2.0.zip, aether-1.20.1-1.4.2-neoforge.jar:packs/tips, file/Fancy Crops v1.0 f5-34.zip, builtin/overrides/golden_swet_ball/DAGoldenSwetBallFixClient, resource/overrides_pack, aether-redux-2.0.17-1.20.1-neoforge.jar:packs/resource/redux_tips, file/boss-refreshed-v1.4.zip, file/Aether Regenerated v1.2.1.zip, file/AnimEmis_spartanfire_1.20.1.zip, file/nongko's_Fantasy_Weapons_v1.14.zip, file/miles's Enchanted Weapons v2.7.zip, file/!§bKnightArmor.zip, file/updated_aquaculture-1.0.zip, file/Realistic Combat Soundpack 2.0.zip, diagonalblocks:default_block_models
Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,re:classloading,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadEnd,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinResourceReload,pl:mixin:APP:biomemusic.mixins.json:ReloadHookMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2326) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.3.11.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by hallowfiend** [comment]
I have this issue as well.
