### ISSUE TITLE
Viewing a primordial caves map crashes the game and makes the world inaccessible

### ISSUE THREAD

**Issue by KalebMorton** [AlexModGuy/AlexsCaves#576]
I tried to view a primordial cave map and it crashed my game. anytime I try to re-enter the world the game crashes again. This happed on the most recent version of the mod, but the map and the cave itself was generated on an older version of the mod (1.0.4).

Here's the crash report:

Time: 2023-11-09 11:18:48
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.github.alexmodguy.alexscaves.server.item.CaveMapItem.createBiomeArray(CaveMapItem.java:97) ~[alexscaves-1.0.7.jar%23161!/:1.0.7] {re:classloading,re:mixin}
	at com.github.alexmodguy.alexscaves.client.render.misc.CaveMapRenderer.getMapFor(CaveMapRenderer.java:71) ~[alexscaves-1.0.7.jar%23161!/:1.0.7] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.ItemInHandRenderer.renderCaveMap(ItemInHandRenderer.java:708) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.renderTwoHandedCaveMap(ItemInHandRenderer.java:731) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.handler$zck000$ac_renderArmWithItem(ItemInHandRenderer.java:663) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109371_(ItemInHandRenderer.java) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:317) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:852) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1132) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.alexmodguy.alexscaves.server.item.CaveMapItem.createBiomeArray(CaveMapItem.java:97) ~[alexscaves-1.0.7.jar%23161!/:1.0.7] {re:classloading,re:mixin}
	at com.github.alexmodguy.alexscaves.client.render.misc.CaveMapRenderer.getMapFor(CaveMapRenderer.java:71) ~[alexscaves-1.0.7.jar%23161!/:1.0.7] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.ItemInHandRenderer.renderCaveMap(ItemInHandRenderer.java:708) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.renderTwoHandedCaveMap(ItemInHandRenderer.java:731) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.handler$zck000$ac_renderArmWithItem(ItemInHandRenderer.java:663) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109371_(ItemInHandRenderer.java) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:317) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:alexscaves.mixins.json:client.ItemInHandRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:852) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1132) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Rocky_707'/474, l='ClientLevel', x=-227.34, y=69.00, z=8.25]]
	Chunk stats: 5041, 1035
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,118,0), Section: (at 0,6,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4550071 game time, 5527590 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:alexscaves.mixins.json:client.ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 937089024 bytes (893 MiB) / 2894069760 bytes (2760 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i9-13900K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 32
	Graphics card #0 name: Intel(R) UHD Graphics 770
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0xa780
	Graphics card #0 versionInfo: DriverVersion=31.0.101.4502
	Graphics card #1 name: NVIDIA GeForce RTX 4090
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2684
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3640
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 74913.58
	Virtual memory used (MB): 20896.49
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Launched Version: forge-47.2.0
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 4090/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.40, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: vanilla, mod_resources
	Current Language: en_us
	CPU: 32x 13th Gen Intel(R) Core(TM) i9-13900K
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Rocky_707'/474, l='ServerLevel[Caves2]', x=-227.34, y=69.00, z=8.25]]
	Data Packs: vanilla, mod:forge, mod:citadel (incompatible), mod:alexscaves, mod:puzzleslib, mod:easyanvils, mod:stackablepotions (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		PuzzlesLib-v8.0.24-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.0.24              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Stackable Potions-forge-1.20.1-1.0.0.jar          |Stackable Potions             |stackablepotions              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		EasyAnvils-v8.0.1-1.20.1-Forge.jar                |Easy Anvils                   |easyanvils                    |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		citadel-2.4.9-1.20.1.jar                          |Citadel                       |citadel                       |2.4.9               |DONE      |Manifest: NOSIGNATURE
		alexscaves-1.0.7.jar                              |Alex's Caves                  |alexscaves                    |1.0.7               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f2a81fb5-5c97-4926-978d-9834f77ca708
	FML: 47.2
	Forge: net.minecraftforge:47.2.0

**Comment by AlexModGuy** [comment]
https://modrinth.com/mod/alexs-caves/versions/1.0.8
> Curseforge is actively restricting me from uploading the latest build to the website because they have placed new file(s) under 'Manual Review' for multiple days now.
