### ISSUE TITLE
Magnetic Caves consistently crashing

### ISSUE THREAD

**Issue by tavvyhiggins** [AlexModGuy/AlexsCaves#661]
no other mods besides this mod, citadel and the essential mod. Whenever me or one of my friends enters the magnetic caves the game crashes doesn't matter if it's singleplayer or multiplayer

[2023-11-23-4.log.gz] (https://github.com/AlexModGuy/AlexsCaves/files/13454358/2023-11-23-4.log.gz)

[2023-11-23-3.log.gz] (https://github.com/AlexModGuy/AlexsCaves/files/13454359/2023-11-23-3.log.gz)
 
[2023-11-23-2.log.gz] (https://github.com/AlexModGuy/AlexsCaves/files/13454361/2023-11-23-2.log.gz)

**Comment by AlexModGuy** [comment]
relevant crash:
> java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "this.f_20945_" is null
	at net.minecraft.world.entity.LivingEntity.m_21023_(LivingEntity.java:911) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.world.entity.Entity.handler$zbd000$ac_isInWater(Entity.java:3791) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.world.entity.Entity.m_20069_(Entity.java) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.world.entity.Entity.m_20072_(Entity.java:1180) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at com.github.alexmodguy.alexscaves.server.entity.living.DeepOneMageEntity.isDeepOneSwimming(DeepOneMageEntity.java:245) ~[alexscaves-1.0.6.jar%23162!/:1.0.6]
	at com.github.alexmodguy.alexscaves.server.entity.living.DeepOneBaseEntity.m_6972_(DeepOneBaseEntity.java:395) ~[alexscaves-1.0.6.jar%23162!/:1.0.6]

looking into this.

**Comment by AlexModGuy** [comment]
other issue is #328
