### ISSUE TITLE
Deadlock due to Cycads on server

### ISSUE THREAD

**Issue by jane0009** [AlexModGuy/AlexsCaves#700]
Hi! Recently I've been diagnosing a deadlock on my server and have isolated it to some interaction with this mod and the lighting engine. The server will freeze on a single tick until the watchdog kills it. I have attached a full crash log at the bottom of this issue.

In particular, this section in the log made me think it was due to this mod:

```
"Worker-Main-2" daemon prio=5 Id=68 WAITING on java.util.concurrent.CompletableFuture$Signaller@758d06c8
	
...
	
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:114)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_6522_(Level.java:187)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:129)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_6325_(Level.java:182)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_8055_(Level.java:355)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.handler$zcd000$removeOffset(BlockBehaviour.java:1472)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60824_(BlockBehaviour.java)
	at TRANSFORMER/alexscaves@1.0.8/com.github.alexmodguy.alexscaves.server.block.CycadBlock.m_5940_(CycadBlock.java:57)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60651_(BlockBehaviour.java:676)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60808_(BlockBehaviour.java:672)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour.m_7952_(BlockBehaviour.java:271)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60768_(BlockBehaviour.java:559)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60804_(BlockBehaviour.java:659)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour.m_7753_(BlockBehaviour.java:289)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60739_(BlockBehaviour.java:551)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.lighting.LightEngine.m_284404_(LightEngine.java:79)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.lighting.BlockLightEngine.m_284316_(BlockLightEngine.java:57)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.lighting.LightEngine.m_284361_(LightEngine.java:170)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.lighting.LightEngine.m_9323_(LightEngine.java:150)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.lighting.LevelLightEngine.m_9323_(LevelLightEngine.java:53)
	
...
```

After backing up the world and removing the mod, the issue went away. Re-adding the mod and disabling the primordial caves biome, which was the biome in question causing the issue, and deleting the region file with the problem area does not seem to resolve the issue, so I suspect that the issue is present in multiple biomes from this mod.

I'm unsure how to go about diagnosing the issue any further, so any help would be appreciated.

Crash log:
[crash-2023-12-09_22.53.51-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/13626558/crash-2023-12-09_22.53.51-server.txt)

**Comment by jane0009** [comment]
noticed #48 this is probably a dupe of that
