### ISSUE TITLE
Alexs cave crashes modpack on launch after updating to latest version

### ISSUE THREAD

**Issue by EarthKing339** [AlexModGuy/AlexsCaves#826]
Heres a doc with the log on it cuz log was too long to copy paste here directly https://docs.google.com/document/d/1bh4Cgb_bmEW9sNsfZi4jVfj3IsIKrS22r3HHyCc7Ymc/edit

**Comment by AlexModGuy** [comment]
your url here is access protected.

**Comment by EarthKing339** [comment]
How do I make it not access protected???

**Comment by AlexModGuy** [comment]
idk. use pastebin or something else other than a password protected google doc.

**Comment by EarthKing339** [comment]
Okay

**Comment by StrayDN** [comment]
I join the thread so as not to create another.
The same thing happens to me, I don't know if this information is useful.

Description: Ticking entity

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.world.entity.item.ItemEntity)
	Entity ID: 120
	Entity Name: Void Block
	Entity's Exact location: -11.24, -Infinity, 101.67
	Entity's Block location: World: (-12,2147483647,101), Section: (at 4,15,5 in -1,134217727,6; chunk contains blocks -16,-128,96 to -1,319,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-128,0 to -1,319,511)
	Entity's Momentum: Infinity, -Infinity, Infinity
	Entity's Passengers: []
	Entity's Vehicle: null

[Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Start element (9223367638808264704) is larger than end element (-9223372036854775808)
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet$Subset.<init>(LongAVLTreeSet.java:1080) ~[fastutil-8.5.9.jar%23129!/:?]
	at it.unimi.dsi.fastutil.longs.LongAVLTreeSet.subSet(LongAVLTreeSet.java:1047) ~[fastutil-8.5.9.jar%23129!/:?]
	at net.minecraft.world.level.entity.EntitySectionStorage.m_188362_(EntitySectionStorage.java:57) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.world.level.entity.EntitySectionStorage.m_261111_(EntitySectionStorage.java:122) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.world.level.entity.LevelEntityGetterAdapter.m_142232_(LevelEntityGetterAdapter.java:43) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.world.level.Level.m_6249_(Level.java:641) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.world.level.EntityGetter.m_183134_(EntityGetter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.world.level.CommonLevelAccessor.m_183134_(CommonLevelAccessor.java:23) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.world.entity.Entity.handler$fnb000$ac_collide(Entity.java:19721) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.world.entity.Entity.m_20272_(Entity.java) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.world.entity.Entity.m_6478_(Entity.java:632) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.world.entity.item.ItemEntity.m_8119_(ItemEntity.java:138) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%231134!/:?]
	... 5 more

**Comment by AlexModGuy** [comment]
> I join the thread so as not to create another. The same thing happens to me, I don't know if this information is useful.

Don't do that unless you're sure this is the same issue. And since OP hasnt posted any log whatsoever at this point, I suggest you move this to a new ticket.

**Comment by AlexModGuy** [comment]
@EarthKing339 did you fix your file upload issues?
