### ISSUE TITLE
Primordial Caves not loading (Maybe more)

### ISSUE THREAD

**Issue by Jasdernn** [AlexModGuy/AlexsCaves#84]
For, some reason, Primordial Caves for me aren't generating. It just stops generating and leaves a giant hole. It's kind of like when you're flying in creative mode to a biome or something in an unloaded chunk and it stops you from going any further for a second and then when the chunk is loaded it allows you to fly through it again (sorry for the awful explanation). And usually when I encounter this, on the saving world screen it just freezes. Like I can't even close Minecraft I need to restart my computer to close Minecraft.  I will try to post more issues if necessary.

Mods installed are:
Alex's Caves and Citadel (Duh)
Alex's Mobs
Cloud Storage
Domestication Innovation
Twigs with Geckolib
Xaeros World Map
Zetter
And Farmer's Delight

![2023-10-19_16 56 08](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/907de284-6b86-4a60-a1df-416ece9ca907)
![2023-10-19_17 10 47](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/d2131b92-0d59-4a57-a719-9110466e40b9)

Hopefully this helps

**Comment by Jasdernn** [comment]
Update: All the mobs can't move either, so it just freezes the game indefinitely.

**Comment by AlexModGuy** [comment]
incompatible with Twigs

**Comment by Jasdernn** [comment]
dang, I loved that mod.

**Comment by Jasdernn** [comment]
But, why only the primordial caves? I mean I've been to the Magnetic Caves and Toxic Caves and there was no problem.

**Comment by rainysux** [comment]
I just visited the primordial with twigs enabled and it works

**Comment by BadgerKing21** [comment]
Not to be annoying, but is there a patch for this issue coming around soon?

**Comment by AlexModGuy** [comment]
The few server side logs of the hanging seem to reference block collision gathering:
> 	at net.minecraft.world.level.Level.m_7925_(Level.java:635) ~[server-1.20.1-20230612.114412-srg.jar%23347!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:A}
	at net.minecraft.world.level.BlockCollisions.m_186411_(BlockCollisions.java:62) ~[server-1.20.1-20230612.114412-srg.jar%23347!/:?] {re:classloading}
	at net.minecraft.world.level.BlockCollisions.computeNext(BlockCollisions.java:81) ~[server-1.20.1-20230612.114412-srg.jar%23347!/:?] {re:classloading}

The few mixins that both Twigs and Etcetera share in common include this mixin into blockstate collisions:
https://github.com/moddingplayground/twigs-forge/blob/1.19/src/main/java/net/moddingplayground/twigs/mixin/BlockStateBaseMixin.java#L17C17-L17C26
https://github.com/N1nn1/etcetera/blob/main/src/main/java/com/ninni/etcetera/mixin/AbstractBlockStateMixin.java#L18

This is likely indirectly causing this issue.

**Comment by AlexModGuy** [comment]
I'm not too sure as to what could be causing the issue in Twigs - from what I can see, it's simply checking the block that is currently in the blockstate and going from there. However, this is code from 1.19 - I cannot seem to find any repo for Twigs 1.20+, though I may be looking in the wrong place. If anyone could link the relevant 1.20.1 code that would be appreciated. 

For Etcetera, the problem becomes a lot clearer to see.
https://github.com/N1nn1/etcetera/blob/main/src/main/java/com/ninni/etcetera/mixin/AbstractBlockStateMixin.java#L21-L22
> if (world.getBlockState(pos.down(1)).isIn(EtceteraTags.OFFSET_REMOVER)
                || (that.getBlock() instanceof TallPlantBlock && world.getBlockState(pos.down(2)).isIn(EtceteraTags.OFFSET_REMOVER))

Right here, there is a querry being made to the level to load in the two blocks immediately beneath any given Plant block. There is no checking if these block positions are in a loaded chunk - meaning this code would force unloaded chunks to attempt to load, thus causing ticks to take too long. It would also explain why we only see this error in Primordial Caves and Abyssal Chasms - the other biomes in the mod don't really have 'Plant' blocks (such as the Ping-Pong Sponge and Venus Flytrap).

**Comment by PeglinX** [comment]
Don’t know if you already got this or I’m misinterpreting what you asked for but I’m pretty sure this has Twigs 1.20.1 code on the repository https://github.com/N1nn1/twigs

**Comment by calinado** [comment]
had this same exact issue and finally found this thread to solve it. I wish twigs was compatible but removing it for the massive content Alex's Caves offers is definitely okay with me.

@AlexModGuy im not sure if any of this helps, but here are tons of crash logs and pastebin crap from my issues before I found this thread: https://www.reddit.com/r/admincraft/comments/19du63g/single_server_tick_took_60000_seconds/

***Here is my most recent crash report before uninstalling Twigs- https://gist.github.com/calinado/9449906f3d703b43b5b9e9c4e5a85382

I was removing tons of mods that I thought would be causing the issue when Twigs was the culprit all along, so dont mind the dozens of removed mod errors. it basically stalled my server and Watchdog inevitably crashed everything

summarized links:
https://pastebin.com/Nxky8pZf
https://spark.lucko.me/iLNKht76kl
https://gist.github.com/calinado/e8a51c702d053c75ea572123e1043ea1#file-gistfile1-txt

**Comment by PeglinX** [comment]
Is this planned to be fixed soon or still in back burner

**Comment by TinyMuteLizard** [comment]
Hallo, it is April 2025, this issue still persists and is currently plaguing me. The same map that runs perfectly fine on singleplayer crashes my dedicated the second it loads in deep_ocean or the abyssal depths or the slightest whif of a chunk connected to it. Every other ocean related mod was removed, it still does this. Its Alex Caves with Twigs and Etc on a 1.20.1 Forge. 

Im telling you nothing new, but since this issue stands unresolved i thought i bring it up again.

Even if not that helpful i kind of want to share my experience with this biome? In hundreds - and i mean hundreds - of attempts of world generation in which i tried to find the abyssal depths, they were found a total of 6 (!) times, of which one was a fluke (technically two but i will not count one map twice), three times were crashing/timing out the server and the two times where it DID work, the depths were so messed up like i have not seen before outside of a no-rule server spawn. This biome seems to suck up every random bit of modded structure it can, as long as its supposed to be remotely underground and not just that. Like, i get running huge modpacks like that is asking for trouble, but this is the only case in which this has ever occurred. There must be some kind of larger, underlying issue here or something that explains this... Like, it smashes an underground catacomb from Born in Chaos into a Trial Chamber from Better Trial Chambers and somewhere there is a random room floating with a single zombie inside, which is from a mod that is really just adding about 10 tiny tiny 5x5 rooms to the underground and nothing else. I also.. both times... had an ocean monument just hang there with a few other buildings that shouldnt be on the water being exactly on the water. Also, roughly around that height level where all this garbage is cluttering the ocean, the shaders spasm out... I wish i had something more helpful to say but i can only describe this madness.

**Comment by thelegitdolt** [comment]
https://modrinth.com/mod/dolt-mod-how/version/2.3.6 my mod has a fix for the crash with etcetera via using mixinsquared to disable the mixin. yall can take a look if you want

**Comment by PeglinX** [comment]
Anyone has any other fix in the meantime I don’t wanna use Quark (needed for Dolt Mod How), it doesn’t necessarily need to be a permanent fix, just something to be able to play again.

**Comment by rafaelkai** [comment]
@thelegitdolt Is there any chance you could release just the crash fix as a standalone mod? It would be highly appreaciated
